-- AlterTable
ALTER TABLE `Client`
  ADD COLUMN `direction` ENUM('REPASSAR', 'RECEBER') NOT NULL DEFAULT 'REPASSAR',
  ADD COLUMN `siteSalePrice` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `companyAmount` DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `partnerAmount` DECIMAL(10, 2) NOT NULL DEFAULT 5;
